### ISSUE TITLE
LWUTIL_ABS does not always return positive value

### ISSUE THREAD

**Issue by ra1u** [MaJerle/lwutil#3]
From [lwutil.h:77](https://github.com/MaJerle/lwutil/blob/01aa3a8b985d05e25362e42fd68d5e97dbc8931f/lwutil.h#L77)

```
int main()
{
    int i = -2147483648;
    printf("%d,%d",i,LWUTIL_ABS(i));

    return 0;
}
```

Prints 
 -2147483648 -2147483648

**Comment by MaJerle** [comment]
You sure it is problem of abs function or rather printf with %d. Test with %u instead, for result of abs.

printf("%d,%u",i,(unsigned)LWUTIL_ABS(i));

**Comment by ra1u** [comment]
I am not sure, that problem is with _%d_. Issue is that largest _int32_t_ is 2147483647 and thus as expected return value of _ABS_ that is 2147483648 can not be represented. Is just how binary representation works. 

There is similar issue with `intmax_t imaxabs(intmax_t j);` from `inttypes.h`. However, [C standard 7.8.2.1](https://port70.net/~nsz/c/c11/n1570.html#7.8.2.1) here clearly states  
_The imaxabs function computes the absolute value of an integer j. If the result cannot be represented, the behavior is undefined._

Similar remark as from C standard is missing for macro _LWUTIL_ABS_ description. There is not much that can be done here.   
I just pointed out, that _LWUTIL_ABS_ does not _returns always-positive value_ as stated in description.

**Comment by MaJerle** [comment]
I disagree here. One thing is C standard and its function that accepts (intmax_t). My macro accepts any option, so if you believe that your (int32_t) variable is out of bounds, cast result to int64_t or event better, make it (uint32_t) instead.

So macro will rotate bits (as you said, that's what binary is) and if data is properly and well handled, it will work well too.

This example:
```
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

#define LWUTIL_ABS(x)                           ((x) < 0 ? -(x) : (x))
#define INT_MIN_VAL                             (-2147483648)

int main(void) {
    uint32_t var = LWUTIL_ABS((-2147483648));
    printf("%d\r\n", (int32_t)INT_MIN_VAL);
    printf("%d\r\n", (int32_t)LWUTIL_ABS(INT_MIN_VAL));
    printf("%lu\r\n", (unsigned long)LWUTIL_ABS(INT_MIN_VAL));
    return 0;
}
```

Prints:
```
-2147483648
-2147483648
2147483648
```

I do agree with you on the point that if you input very minimum of the var, it must be well handled then since you need longer data representation.

Nevertheless, macro works properly, it is how you handle returned data and how printf works. `%d` in printf is equal to `*(int *)pointer_to_var`, while with `%u`, it is `*(unsigned *)pointer_to_var`.

**Comment by ra1u** [comment]
What I am saying is that macro is not doing what is sais that it is doing.
What it says is doing:  
_Absolute value of the input value - Returns always-positive value of the input_   
And as you have also demonstrated it is not _always_ the case.

**Comment by MaJerle** [comment]
I will close this issue as it is not an issue. You are welcome to propose a pull-request and I will merge it.

Macro returns positive value, however if you write it to smaller value than value needs, you cannot expect correct result (or even %d for print).

Pointless to discuss further.
